### ISSUE TITLE
$filter('filter') on query result

### ISSUE THREAD

**Issue by thochi** [simplicitylabs/angular-thickm#4]
Hi,

i'm wondering that i can only use $filter by applying $.makeArra before. E.g:

```
$filter('filter')($.makeArray(result_collection), 'foo');
```

Is this intended. Will it work in templates?

Btw, nice library!

**Comment by mikberg** [comment]
Thanks!

This is probably related to angular/angular.js#7143 and how angular checks if an object is an array. It's not intended, but not easily fixable.
